### ISSUE TITLE
An infrared image dehazing method based on Modified Dark Channel Prior

### ISSUE THREAD

**Issue by ghost** [FightingZxw/test#3]
学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？
扣：1178156199

**Comment by FightingZxw** [comment]
这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。




曾祥伟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FightingZxw/test"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月3日(星期六) 晚上11:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3)





 
学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？
 扣：1178156199

**Comment by ghost** [comment]
> 这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。 曾祥伟 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" ***@***.***&gt;; 发送时间:&nbsp;2022年12月3日(星期六) 晚上11:00 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？ 扣：1178156199 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by ghost** [comment]
> > 这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。 曾祥伟 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "FightingZxw/test" _**@**_._**>; 发送时间: 2022年12月3日(星期六) 晚上11:00 _**@**_.**_>; _**@**_._**>; 主题: [FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？ 扣：1178156199 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>

红外雾天图像不应该是单通道的么？我发现他给我的都不是单通道的，您知道哪里有现成的“红外雾天图像”数据么？想用来做下仿真实验，谢谢您

**Comment by FightingZxw** [comment]
我这边暂时没有，你可以去看下网上开源的数据集！




曾祥伟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FightingZxw/test"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3)





   
这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。 曾祥伟 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" @.&gt;; 发送时间:&nbsp;2022年12月3日(星期六) 晚上11:00 _@**._&gt;; ***@***.***&gt;; 主题:&nbsp;[FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？ 扣：1178156199 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.**_&gt;
   
红外雾天图像不应该是单通道的么？我发现他给我的都不是单通道的，您知道哪里有现成的“红外雾天图像”数据么？想用来做下仿真实验，谢谢您

**Comment by ghost** [comment]
> 我这边暂时没有，你可以去看下网上开源的数据集！ 曾祥伟 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" ***@***.***&gt;; 发送时间:&nbsp;2022年12月14日(星期三) 中午11:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。 曾祥伟 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" @.&gt;; 发送时间:&nbsp;2022年12月3日(星期六) 晚上11:00 _@**._&gt;; ***@***.***&gt;; 主题:&nbsp;[FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？ 扣：1178156199 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.**_&gt; 红外雾天图像不应该是单通道的么？我发现他给我的都不是单通道的，您知道哪里有现成的“红外雾天图像”数据么？想用来做下仿真实验，谢谢您 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢您啊，我在网上找了，好像没有“红外雾天图像”这个类别，我看之前那篇文章用pix2pix来生成的，竟然不是单通道的，疑惑。无论如何还是感谢您哈！

**Comment by FightingZxw** [comment]
没事，之前那篇文章比较水，不值得深入研究。然后数据集还是需要自己去拍摄比较好！网上数据集和论文参差不齐！




曾祥伟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FightingZxw/test"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月17日(星期六) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3)





  
我这边暂时没有，你可以去看下网上开源的数据集！ 曾祥伟 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" @.&gt;; 发送时间:&nbsp;2022年12月14日(星期三) 中午11:00 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 这个你可以问下原作者，据说她用pix2pix合成了红外雾天图像，但是我是存在质疑的。 曾祥伟 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FightingZxw/test" @.&gt;; 发送时间:&nbsp;2022年12月3日(星期六) 晚上11:00 @**.&gt;; @.&gt;; 主题:&nbsp;[FightingZxw/test] An infrared image dehazing method based on Modified Dark Channel Prior (Issue #3) 学者您好，看您研究过这篇论文，在作者下面提过issues，想请教您点关于红外雾天图像数据集的问题，方便加您联系方式么？ 扣：1178156199 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @._&gt; 红外雾天图像不应该是单通道的么？我发现他给我的都不是单通道的，您知道哪里有现成的“红外雾天图像”数据么？想用来做下仿真实验，谢谢您 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.**&gt;
  
谢谢您啊，我在网上找了，好像没有“红外雾天图像”这个类别，我看之前那篇文章用pix2pix来生成的，竟然不是单通道的，疑惑。无论如何还是感谢您哈！
